/*
 * The Tutor: turns what you saved into what you know.
 *
 * Saving an article is not learning it, and the gap between the two is the
 * reason read-later apps fill up and never empty. This makes cards from your
 * own material and schedules them, so the archive stops being a pile and
 * starts being a queue with an end.
 *
 * Cards are cut from passages by rule, not written by a model. A cloze made
 * by deleting the load-bearing term from a sentence you saved is a question
 * whose answer is certainly in your material; a question generated by a model
 * is a question whose answer might be. For a tool whose whole promise is that
 * it only tells you things you can trace, that difference decides it.
 *
 * Scheduling is SM-2, the SuperMemo algorithm the whole spaced-repetition
 * field is built on (Wozniak & Gorzelanczyk, 1994). Not reinvented: the
 * interesting work here is choosing what to ask, and the interval maths has
 * been settled for thirty years.
 */

import { hashId } from '../core/id.js'
import { iso } from '../core/time.js'
import { tokenise } from '../stash/search.js'

const DAY = 86400000

/* Words too common to be worth hiding: a cloze over "the" teaches nothing. */
const COMMON = new Set([
  'the', 'a', 'an', 'and', 'or', 'but', 'is', 'was', 'are', 'were', 'be', 'been', 'being',
  'has', 'have', 'had', 'of', 'to', 'in', 'on', 'at', 'for', 'from', 'by', 'with', 'as',
  'it', 'its', 'this', 'that', 'these', 'those', 'they', 'them', 'their', 'we', 'our',
  'not', 'no', 'so', 'if', 'then', 'than', 'when', 'while', 'which', 'who', 'what',
  'will', 'would', 'can', 'could', 'should', 'may', 'might', 'do', 'does', 'did',
])

export const emptyCard = () => ({
  id: '',
  question: '',
  answer: '',
  source: '',
  kind: 'cloze',
  // SM-2 state.
  ease: 2.5,
  interval: 0,
  repetitions: 0,
  due: '',
  lapses: 0,
  lastGrade: null,
})

/**
 * The term worth hiding in a sentence.
 *
 * The rarest content word, because rarity is the best available proxy for
 * "the word this sentence is actually about" without understanding the
 * sentence. Numbers and capitalised terms are preferred outright - a date, a
 * threshold or a name is almost always the thing worth remembering.
 */
export function keyTerm(sentence, frequencies = new Map()) {
  const words = String(sentence ?? '').split(/\s+/).filter(Boolean)
  let best = null
  let bestScore = -Infinity
  for (const raw of words) {
    const word = raw.replace(/^[^\w%$]+|[^\w%$]+$/g, '')
    if (word.length < 3) continue
    const lower = word.toLowerCase()
    if (COMMON.has(lower)) continue

    // A figure is the fact; an identifier that merely contains digits is
    // usually its label. Hiding "264" in "p99 latency was 264 ms" makes a
    // card worth answering; hiding "p99" makes one that tests nothing.
    const isFigure = /^[+-]?[\d.,]+[a-z%]{0,4}$/i.test(word)
    const hasDigits = /\d/.test(word)
    const isProper = /^[A-Z][a-z]/.test(word)
    const rarity = 1 / (1 + (frequencies.get(lower) || 0))
    const score = rarity + (isFigure ? 2 : hasDigits ? 0.75 : 0) + (isProper ? 0.5 : 0)
    if (score > bestScore) { bestScore = score; best = word }
  }
  return best
}

/** A term is a literal, and a term like "c++" or "CVE-2024" is a literal full
    of regex metacharacters. */
const escapeTerm = (term) => String(term).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const sentences = (text) =>
  String(text ?? '')
    .replace(/\[\[[^\]]+\]\]/g, ' ')
    .split(/(?<=[.!?])\s+|\n+/)
    .map((s) => s.trim())
    .filter((s) => s.split(/\s+/).length >= 6 && s.split(/\s+/).length <= 40)

/**
 * Cards from passages.
 *
 * One card per passage at most. Ten cloze deletions from one paragraph is ten
 * ways to ask the same thing, and a queue full of those is how people quit.
 */
export function cardsFrom(passages, { now = new Date(), limit = 20 } = {}) {
  const frequencies = new Map()
  for (const p of passages) {
    for (const word of tokenise(`${p.title} ${p.excerpt?.text || p.text || ''}`)) {
      frequencies.set(word, (frequencies.get(word) || 0) + 1)
    }
  }

  const cards = []
  for (const passage of passages) {
    if (cards.length >= limit) break
    // The passage, not the excerpt. An excerpt is the window around the query
    // match with its whitespace collapsed, so the line breaks that separate a
    // title from its body are gone and the "sentence" is both at once.
    const body = passage.text || passage.title || ''
    for (const sentence of sentences(body)) {
      const term = keyTerm(sentence, frequencies)
      if (!term) continue
      // Every occurrence, not the first. A sentence that says "264" twice
      // would otherwise print the answer next to the blank.
      const question = sentence.replace(new RegExp(escapeTerm(term), 'g'), '______')
      if (question === sentence) continue
      cards.push({
        ...emptyCard(),
        id: hashId('card', `${passage.id}:${sentence.toLowerCase()}`),
        question,
        answer: term,
        source: passage.id,
        due: iso(now),
      })
      break // one per passage
    }
  }
  return cards
}

/**
 * SM-2.
 *
 * `grade` is 0-5 as the algorithm defines it; the UI offers four of them.
 * Below 3 is a lapse: the interval resets and the card comes back today,
 * because a card you could not answer is not one to see again in six days.
 */
export function schedule(card, grade, { now = new Date() } = {}) {
  const g = Math.max(0, Math.min(5, Math.round(Number(grade) || 0)))
  const next = { ...card, lastGrade: g }

  if (g < 3) {
    next.repetitions = 0
    next.interval = 0
    next.lapses = card.lapses + 1
    next.due = iso(now)
    // The ease floor is 1.3 in the original and stays there: below it the
    // intervals collapse and the card is shown forever.
    next.ease = Math.max(1.3, card.ease - 0.2)
    return next
  }

  next.repetitions = card.repetitions + 1
  if (next.repetitions === 1) next.interval = 1
  else if (next.repetitions === 2) next.interval = 6
  else next.interval = Math.round(card.interval * card.ease)

  next.ease = Math.max(1.3, card.ease + (0.1 - (5 - g) * (0.08 + (5 - g) * 0.02)))
  next.due = iso(new Date(now.getTime() + next.interval * DAY))
  return next
}

/** What to study now, hardest first: a lapsed card earns its place at the
    front, because the ones you keep failing are the ones worth the session. */
export function queue(cards, { now = new Date(), limit = 20 } = {}) {
  const at = now.getTime()
  return cards
    .filter((c) => !c.due || Date.parse(c.due) <= at)
    .sort((a, b) => b.lapses - a.lapses || Date.parse(a.due || 0) - Date.parse(b.due || 0))
    .slice(0, limit)
}

/** Where the queue stands, for a screen that should say so honestly. */
export function progress(cards, { now = new Date() } = {}) {
  const at = now.getTime()
  const due = cards.filter((c) => !c.due || Date.parse(c.due) <= at).length
  const learned = cards.filter((c) => c.repetitions >= 3 && c.interval >= 21).length
  return {
    total: cards.length,
    due,
    learned,
    lapsing: cards.filter((c) => c.lapses >= 3).length,
  }
}
