apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: alldash
  labels:
    app.kubernetes.io/name: postgres
    backup: daily
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: alldash-gp3
  resources:
    requests:
      storage: 20Gi
